{%- from "kubernetes/map.jinja" import common with context -%}
{%- from "kubernetes/map.jinja" import master with context -%}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: {{ common.addons.coredns.namespace }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  Corefile: |
    .:53 {
{% if master.federation.enabled %}
        etcd {{ master.federation.name }} {
          stubzones
          path /skydns
          endpoint http://{{ common.addons.coredns.etcd.client_address }}:2379
        }
{% endif %}
{% if common.addons.externaldns.enabled %}
        etcd {{ common.addons.externaldns.domain }} {
          stubzones
          path /skydns
          endpoint http://{{ common.addons.coredns.etcd.client_address }}:2379
        }
{% endif %}
        errors
        log stdout
        health
        proxy . /etc/resolv.conf
        cache 30
        reload
        loadbalance
        kubernetes {{ common.addons.coredns.domain|replace('_', '-') }}. in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
    }
