{%- from "kubernetes/map.jinja" import common with context %}
{%- from "kubernetes/map.jinja" import master with context %}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: {{ common.addons.coredns.namespace }}
  addonmanager.kubernetes.io/mode: Reconcile
data:
  Corefile: |
    .:53 {
        etcd {{ master.federation.name }} {
          stubzones
          path /skydns
          endpoint http://coredns-etcd:2379
        }
        errors
        log stdout
        health
        proxy . /etc/resolv.conf
        cache 30
    }
