{%- from "kubernetes/map.jinja" import common with context -%}
---
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  namespace: {{ common.addons.coredns.namespace }}
  name: coredns-etcd-cluster
  labels:
    app: coredns-etcd-operator
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  size: 3
  version: {{ common.addons.coredns.etcd.version }}
  baseImage: {{ common.addons.coredns.etcd.base_image }}
