{%- from "kubernetes/map.jinja" import common with context %}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ common.addons.coredns.namespace }}
  labels:
    app: coredns-etcd
    addonmanager.kubernetes.io/mode: Reconcile
  name: coredns-etcd
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      name: coredns-etcd
  template:
    metadata:
      labels:
        name: coredns-etcd
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
      - command:
        - /usr/local/bin/etcd
        - --name
        - coredns-etcd
        - --listen-peer-urls
        - http://0.0.0.0:2380
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://coredns-etcd:2379
        - --initial-cluster-state
        - new
        image: {{ common.addons.coredns.etcd_image }}
        name: coredns-etcd
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP
      restartPolicy: Always
