{%- from "kubernetes/map.jinja" import master with context %}
apiVersion: v1
kind: Endpoints
metadata:
  name: kube-ui
  namespace: kube-system
  labels:
    k8s-app: kube-ui
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeUI"
subsets:
  - addresses:
    - ip: {{ master.addons.ui.public_ip }}

    ports:
    - port: 8080
      protocol: TCP