{%- from "kubernetes/map.jinja" import master with context %}
apiVersion: v1
kind: Service
metadata:
  name: kube-ui-address
  namespace: kube-system
  labels:
    k8s-app: kube-ui
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeUI"
spec:
  selector:
    k8s-app: kube-ui
  deprecatedPublicIPs: ["{{ master.addons.ui.public_ip }}"]
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080