---
driver:
  name: docker
  hostname: kubernetes
  use_sudo: true

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: kubernetes
  grains:
    noservices: True
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux

  state_top:
    base:
      "*":
        - linux
        - kubernetes
  pillars:
    top.sls:
      base:
        "*":
          - linux_repo_docker
          - linux_repo_opencontrail
          - linux
          - kubernetes
    linux.sls:
      linux:
        system:
          enabled: true
          name: kubernetes
  pillars-from-files:
    linux_repo_docker.sls: tests/pillar/repo_docker.sls
    linux_repo_opencontrail.sls: tests/pillar/repo_contrail.sls

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%= ENV['PLATFORM'] || 'ubuntu-xenial' %>
    driver_config:
      image: <%= ENV['PLATFORM'] || 'trevorj/salty-whales:xenial' %>
      platform: ubuntu

suites:

  - name: master_cluster
    provisioner:
      pillars-from-files:
        kubernetes.sls: tests/pillar/master_cluster.sls
  - name: pool_cluster
    provisioner:
      pillars-from-files:
        kubernetes.sls: tests/pillar/pool_cluster.sls

  - name: master_contrail
    provisioner:
      pillars-from-files:
        kubernetes.sls: tests/pillar/master_contrail.sls

  - name: master_contrail4_0
    provisioner:
      pillars-from-files:
        kubernetes.sls: tests/pillar/master_contrail4_0.sls

  - name: pool_contrail4_0
    provisioner:
      pillars-from-files:
        kubernetes.sls: tests/pillar/pool_contrail4_0.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
