suites:

  - name: <%= ENV['SUITE'] %>
    provisioner:
      pillars-from-files:
        <%# to parse SUITE=kubernetes:pillar1,kubernetes_extra:pillar2 %>
        <%- ENV['SUITE'].split(',').each |suite| %>
        <%- set suite = [suite.split(':')].flatten %>
        <%- if suite.length > 1 %>
          <%- set key=suite[0] %>
          <%- set file=suite[1] %>
        <%- else %>
          <%- set key='kubernetes' %>
          <%- set file=suite[0] %>
        <%- end %>
        <%= key %>.sls: tests/pillar/<%= file %>.sls
        <%- end %>
