{%- from "kubernetes/map.jinja" import common with context -%}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: telegraf
  namespace: {{ common.addons.telegraf.get('namespace', 'stacklight') }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: telegraf
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: telegraf
  labels:
    k8s-app: telegraf
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  kind: ClusterRole
  name: telegraf
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: telegraf
  namespace: {{ common.addons.telegraf.get('namespace', 'stacklight') }}
