{%- from "kubernetes/map.jinja" import master with context %}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-network-manager
  namespace: {{ master.addons.kube_network_manager.get('namespace', 'kube-system') }}
data:
  contrail.conf: |
    [DEFAULT]
    master = localhost:8080
    service-cluster-ip-range = {{ master.service_addresses }}

    [opencontrail]
    default-domain = {{ master.network.get('default_domain', 'default-domain') }}
    public-ip-range = {{ master.network.get('public_ip_range', '185.22.97.128/26') }}
    cluster-service = {{ master.network.get('cluster_service', 'kube-system/default') }}
    api-server = 172.16.10.252
    api-port = {{ master.network.get('port', 8082) }}
    default = {{ master.network.get('default_project', 'default-domain:default-project') }}
    public-network = {{ master.network.get('public_network', 'default-domain:default-project:Public') }}
    private-ip-range = {{ master.network.private_ip_range }}
    network-label = {{ master.network.get('network_label', 'opencontrail.org/name') }}
    service-label = {{ master.network.get('service_label', 'opencontrail.org/uses') }}
    service-cluster-ip-range = {{ master.get('service_addresses', '10.254.0.0/16') }}
