{%- from "kubernetes/map.jinja" import master with context %}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kube-network-manager
  namespace: {{ master.addons.kube_network_manager.get('namespace', 'kube-system') }}
spec:
  template:
    metadata:
      labels:
        app: kube-network-manager
    spec:
      hostNetwork: true
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: contrail-kube-manager
          image: {{ master.network.get('image', 'yashulyak/contrail-controller:latest') }}
          imagePullPolicy: Always
          args: ["--config-file", "/etc/kube-manager/contrail.conf", "--alsologtostderr"]
          volumeMounts:
          - name: kube-manager
            mountPath: /etc/kube-manager/
      volumes:
        - name: kube-network-manager
          configMap:
            name: kube-network-manager
      restartPolicy: Always
