{%- from "kubernetes/map.jinja" import common with context -%}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
type: Opaque
data:
{%- for option, value in common.addons.externaldns.aws_options.items() %}
  {{ option }}: {{ salt['hashutil.base64_b64encode'](value) }}
{%- endfor %}
