{%- from "kubernetes/map.jinja" import common with context -%}
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ common.addons.get('alertmanager',{}).get('namespace', 'stacklight') }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
