kind: {{ role_kind }}
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  {%- if role.get('namespace') %}
  namespace: {{ role.namespace }}
  {%- endif %}
  name: {{ role_name }}
{%- if role.get('rules') %}
rules:
  {%- for rule in role.rules %}
  - {{ rule|yaml|indent(2) }}
  {%- endfor %}
{%- endif %}

{#-
vim: syntax=jinja
-#}
