{%- from "kubernetes/map.jinja" import master with context %}
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
  {%- for member in master.storage.members %}
- addresses:
  - ip: {{ member.host }}
  ports: 
  - port: {{ member.port }}
  {%- endfor %}