doc:
  name: Kubernetes
  description: Manage a cluster of Linux containers as a single system to accelerate Dev and simplify Ops.
  role:
  {%- if pillar.kubernetes.pool is defined %}
  {%- from "kubernetes/map.jinja" import client with context %}
    pool:
      name: pool
      param: {}
  {%- endif %}
  {%- if pillar.kubernetes.master is defined %}
    master:
      name: master
      param: {}
  {%- endif %}
