{%- from "kubernetes/map.jinja" import master with context %}
{%- from "kubernetes/map.jinja" import pool with context %}

{%- if pool.get('enabled', False) %}
{% set network = pool.get('network', []) %}
{%- else %}
{%- if master.get('enabled', False) %}
{% set network = master.get('network', []) %}
{% endif %}
{% endif %}

{%- if master.get('enabled', False) or pool.get('enabled', False) %}
agent:
  input:
    procstat:
      process:
  {%- if master.get('enabled', False) %}
        hypercube-apiserver:
          pattern: "hyperkube.*apiserver"
        hypercube-scheduler:
          pattern: "hyperkube.*scheduler"
        hypercube-controller-manager:
          pattern: "hyperkube.*controller-manager"
  {%- endif %}
  {%- if pool.get('enabled', False) %}
        hypercube-kubelet:
          pattern: "hyperkube.*kubelet"
        hypercube-proxy:
          pattern: "hyperkube.*proxy"
  {%- endif %}
  {%- if network is defined and network.get('engine', None) == 'calico' %}
        calico-felix:
          exe: calico-felix
        bird:
          pattern: "bird .*/etc/calico/.*/bird.cfg"
        bird6:
          pattern: "bird6 .*/etc/calico/.*/bird6.cfg"
        confd:
          pattern: "confd .*/etc/calico/confd"
  {%- endif %}
{%- endif %}
