{%- from "kubernetes/map.jinja" import master with context %}
kind: Service
apiVersion: "v1"
metadata:
  name: netchecker
  namespace: {{ master.addons.netchecker.namespace }}
spec:
  selector:
    app: netchecker-server
  ports:
    - protocol: "TCP"
      port: {{ master.addons.netchecker.port }}
      targetPort: {{ master.addons.netchecker.port }}
  type: NodePort
