{%- from "kubernetes/map.jinja" import common with context -%}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netchecker-server
  namespace: {{ common.addons.netchecker.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: netchecker-server
        addonmanager.kubernetes.io/mode: Reconcile
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ common.addons.netchecker.port }}"
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: netchecker-server
          image: {{ common.addons.netchecker.server_image }}
          ports:
            - containerPort: {{ common.addons.netchecker.port }}
          args:
            - "-v=5"
            - "-logtostderr"
            - "-kubeproxyinit"
            - "-endpoint=0.0.0.0:{{ common.addons.netchecker.port }}"
