{%- from "kubernetes/map.jinja" import common with context -%}
kind: Service
apiVersion: "v1"
metadata:
  name: netchecker
  namespace: {{ common.addons.netchecker.namespace }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    app: netchecker-server
  ports:
    - protocol: "TCP"
      port: {{ common.addons.netchecker.port }}
      targetPort: {{ common.addons.netchecker.port }}
  type: NodePort
