{%- from "kubernetes/map.jinja" import common with context -%}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-aggregator-cfg
  namespace: {{ common.addons.fluentd.get('namespace') }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  fluent.conf: |
    @include forward-input.conf
    @include general.conf
    @include output.conf

  forward-input.conf: |
    <source>
      @type forward
      port "#{ENV['FLUENTD_AGGREGATOR_BIND_PORT']}"
      bind 0.0.0.0
    </source>

  general.conf: |
    <match fluent.**>
      @type null
    </match>

  output.conf: |
    <match **>
      @type elasticsearch
      @log_level {{ common.addons.fluentd.aggregator.config.output.elasticsearch.get('log_level') }}
      host "#{ENV['FLUENTD_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENTD_ELASTICSEARCH_PORT']}"
      scheme "#{ENV['FLUENTD_ELASTICSEARCH_SCHEME']}"
      ssl_verify "#{ENV['FLUENTD_ELASTICSEARCH_SSL_VERIFY']}"
      reload_connections "#{ENV['FLUENTD_ELASTICSEARCH_RELOAD_CONNECTIONS']}"
      type_name message
      tag_key Logger
      include_tag_key true
      time_key Timestamp
      time_key_exclude_timestamp true
      logstash_format {{ common.addons.fluentd.aggregator.config.output.elasticsearch.get('logstash_format') | lower }}
      logstash_prefix {{ common.addons.fluentd.aggregator.config.output.elasticsearch.get('logstash_prefix') }}
      logstash_dateformat {{ common.addons.fluentd.aggregator.config.output.elasticsearch.get('logstash_dateformat') }}
      request_timeout {{ common.addons.fluentd.aggregator.config.output.elasticsearch.get('request_timeout') }}
      buffer_chunk_limit {{ common.addons.fluentd.aggregator.config.output.elasticsearch.get('buffer_chunk_limit') }}
      buffer_queue_limit {{ common.addons.fluentd.aggregator.config.output.elasticsearch.get('buffer_queue_limit') }}
      flush_interval {{ common.addons.fluentd.aggregator.config.output.elasticsearch.get('flush_interval') }}
      max_retry_wait {{ common.addons.fluentd.aggregator.config.output.elasticsearch.get('max_retry_wait') }}
      disable_retry_limit
      num_threads {{ common.addons.fluentd.aggregator.config.output.elasticsearch.get('num_threads') }}
    </match>
