{%- from "kubernetes/map.jinja" import common with context -%}
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd-aggregator-svc
  namespace: {{ common.addons.fluentd.get('namespace') }}
  labels:
    k8s-app: fluentd-aggregator
    version: v1
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    k8s-app: fluentd-aggregator
  type: NodePort
  ports:
  - name: input
    port: {{ common.addons.fluentd.aggregator.bind.get('port') }}
    targetPort: {{ common.addons.fluentd.aggregator.bind.get('port') }}
    protocol: TCP
    # must be between 30000-32767
    nodePort: {{ common.addons.fluentd.aggregator.bind.get('host_port') }}
